
server:
  port: 9010
spring:
  profiles:
    active: register0
  application:
    name: register ##name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: register0
  client:
    register-with-eureka: false  # 单节点 设为 false 多节点  高可用的时候  记得改为 true
    fetch-registry: false
    service-url:
      #defaultZone: http://register2:9011/eureka/,http://register2:9012/eureka/
      defaultZone: http://localhost:9010/eureka/
---
server:
  port: 9011
spring:
  profiles: register1
  application:
    name: register ##name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: register1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://register2:9010/eureka/,http://register2:9012/eureka/
      defaultZone: http://register2:9010/eureka/
---
server:
  port: 9012
spring:
  profiles: register2
  application:
    name: register ##name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: register2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://register2:9011/eureka/,http://register2:9010/eureka/
      defaultZone: http://register2:9010/eureka/
