server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http:localhost:8001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eureka-server
