
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gaoxiong-zuul
security:
  oauth2:
    client:
      client-id: gaoxing-zuul
      client-secret: 123456
      user-authorization-uri: http://localhost:8085/uac/oauth/authorize
      access-token-uri: http://localhost:8085/uac/oauth/token
    resource:
#      prefer-token-info: false
      token-info-uri: http://localhost:8085/uac/oauth/token
#    resource:
#      jwt:
#        key-uri: http://localhost:8085/uac/oauth/token_key
zuul:
  routes:
    gaoxiong-server:
      path: /uac/**
      serviceId: gaoxiong-server
      sensitiveHeader:
    client:
      path: /client/**
      serviceId: client-1
      sensitiveHeader:
  ribbon:
    eager-load:
      enabled: true