auth-server: http://localhost:9030/uaa

spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://10.10.8.2:9050
server:
  port: 9030
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://localhost:9010/eureka/
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    oauth2-center:
      path: /uaa/**
#      strip-prefix: true
      sensitiveHeaders:
#      serviceId: oauth2-center
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: ${auth-server}/oauth/token # 引入nginx 的时候 这个地方要输入网关的地址
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri:  ${auth-server}/user
      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
