
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: client-1
#logging:
#  level:
#    root: debug