auth-server: http://localhost:9020/uaa

spring:
  redis:
    host: 106.12.84.16
  datasource:
    url: jdbc:mysql://192.168.2.170:3306/db_auth
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect  # 解决 错误  org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
  application:
    name: oauth2-center
security:
  oauth2:
    resource:
      id: oauth2-center
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
      loadBalanced: true   #OAuth2LoadBalancerClientAutoConfiguration
server:
  port: 9020
  servlet:
    context-path: /uaa
eureka:
  instance:
    hostname: oauth2-center
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true  # 单节点 设为 false 多节点  高可用的时候  记得改为 true
    fetch-registry: true
    service-url:
      #defaultZone: http://register2:9011/eureka/,http://register2:9012/eureka/
      defaultZone: http://localhost:9010/eureka/